import { X, Download, Share2, Info, Edit2 } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';

interface ImageViewerModalProps {
  isOpen: boolean;
  onClose: () => void;
  imageUrl: string;
  title?: string;
  onEdit?: (editPrompt: string) => void;
}

export function ImageViewerModal({ isOpen, onClose, imageUrl, title = 'Image created', onEdit }: ImageViewerModalProps) {
  const [showEditInput, setShowEditInput] = useState(false);
  const [editPrompt, setEditPrompt] = useState('');

  if (!isOpen) return null;

  const handleDownload = async () => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `haitian-chatgpt-image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success('Image downloaded');
    } catch (error) {
      console.error('Download error:', error);
      toast.error('Failed to download image');
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        const response = await fetch(imageUrl);
        const blob = await response.blob();
        const file = new File([blob], 'image.png', { type: 'image/png' });
        await navigator.share({
          files: [file],
          title: title,
        });
      } catch (err) {
        // User cancelled or not supported
        handleCopyLink();
      }
    } else {
      handleCopyLink();
    }
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(imageUrl);
    toast.success('Image link copied');
  };

  const handleInfo = () => {
    toast.info(`Title: ${title}\nGenerated by Dawinix AI`);
  };

  const handleApplyEdit = () => {
    if (onEdit && editPrompt.trim()) {
      onEdit(editPrompt);
      setShowEditInput(false);
      setEditPrompt('');
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black">
      {/* Header */}
      <div className="absolute top-0 left-0 right-0 flex items-center justify-between p-4 bg-black/50 backdrop-blur-sm">
        <div className="flex items-center gap-3">
          <button
            onClick={onClose}
            className="w-11 h-11 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
          >
            <X className="w-6 h-6 text-white" />
          </button>
          <button
            onClick={handleInfo}
            className="w-11 h-11 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
          >
            <Info className="w-6 h-6 text-white" />
          </button>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleDownload}
            className="w-11 h-11 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
          >
            <Download className="w-6 h-6 text-white" />
          </button>
          <button
            onClick={handleShare}
            className="flex items-center gap-2 px-4 py-2 bg-white text-black rounded-full hover:bg-gray-100 transition-colors font-medium"
          >
            <Share2 className="w-5 h-5" />
            Share
          </button>
        </div>
      </div>

      {/* Image */}
      <div className="w-full h-full flex items-center justify-center p-4">
        <img 
          src={imageUrl} 
          alt={title}
          className="max-w-full max-h-full object-contain"
        />
      </div>

      {/* Edit Footer */}
      {onEdit && (
        <div className="absolute bottom-0 left-0 right-0 p-4 bg-black/50 backdrop-blur-sm">
          {!showEditInput ? (
            <button
              onClick={() => setShowEditInput(true)}
              className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-white/10 hover:bg-white/20 rounded-lg transition-colors text-white font-medium"
            >
              <Edit2 className="w-5 h-5" />
              Describe edits
            </button>
          ) : (
            <div className="flex gap-2">
              <input
                type="text"
                value={editPrompt}
                onChange={(e) => setEditPrompt(e.target.value)}
                placeholder="Describe the changes you want to make..."
                className="flex-1 px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-white/30"
                autoFocus
              />
              <Button
                onClick={handleApplyEdit}
                disabled={!editPrompt.trim()}
                className="px-6"
              >
                Apply
              </Button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
