export interface Country {
  name: string;
  code: string;
}

export const COUNTRIES: Country[] = [
  { name: 'United States', code: '+1' },
  { name: 'Canada', code: '+1' },
  { name: 'United Kingdom', code: '+44' },
  { name: 'Australia', code: '+61' },
  { name: 'Germany', code: '+49' },
  { name: 'France', code: '+33' },
  { name: 'Italy', code: '+39' },
  { name: 'Spain', code: '+34' },
  { name: 'Netherlands', code: '+31' },
  { name: 'Belgium', code: '+32' },
  { name: 'Switzerland', code: '+41' },
  { name: 'Austria', code: '+43' },
  { name: 'Sweden', code: '+46' },
  { name: 'Norway', code: '+47' },
  { name: 'Denmark', code: '+45' },
  { name: 'Finland', code: '+358' },
  { name: 'Poland', code: '+48' },
  { name: 'Czech Republic', code: '+420' },
  { name: 'Portugal', code: '+351' },
  { name: 'Greece', code: '+30' },
  { name: 'Ireland', code: '+353' },
  { name: 'New Zealand', code: '+64' },
  { name: 'Japan', code: '+81' },
  { name: 'South Korea', code: '+82' },
  { name: 'China', code: '+86' },
  { name: 'Hong Kong', code: '+852' },
  { name: 'Singapore', code: '+65' },
  { name: 'India', code: '+91' },
  { name: 'Brazil', code: '+55' },
  { name: 'Mexico', code: '+52' },
  { name: 'Argentina', code: '+54' },
  { name: 'Chile', code: '+56' },
  { name: 'Colombia', code: '+57' },
  { name: 'Peru', code: '+51' },
  { name: 'Venezuela', code: '+58' },
  { name: 'South Africa', code: '+27' },
  { name: 'Nigeria', code: '+234' },
  { name: 'Kenya', code: '+254' },
  { name: 'Egypt', code: '+20' },
  { name: 'Morocco', code: '+212' },
  { name: 'Israel', code: '+972' },
  { name: 'Turkey', code: '+90' },
  { name: 'United Arab Emirates', code: '+971' },
  { name: 'Saudi Arabia', code: '+966' },
  { name: 'Qatar', code: '+974' },
  { name: 'Kuwait', code: '+965' },
  { name: 'Russia', code: '+7' },
  { name: 'Ukraine', code: '+380' },
  { name: 'Romania', code: '+40' },
  { name: 'Hungary', code: '+36' },
  { name: 'Croatia', code: '+385' },
  { name: 'Serbia', code: '+381' },
  { name: 'Bulgaria', code: '+359' },
  { name: 'Lithuania', code: '+370' },
  { name: 'Latvia', code: '+371' },
  { name: 'Estonia', code: '+372' },
  { name: 'Iceland', code: '+354' },
  { name: 'Malta', code: '+356' },
  { name: 'Cyprus', code: '+357' },
  { name: 'Luxembourg', code: '+352' },
  { name: 'Monaco', code: '+377' },
  { name: 'Liechtenstein', code: '+423' },
  { name: 'Thailand', code: '+66' },
  { name: 'Vietnam', code: '+84' },
  { name: 'Malaysia', code: '+60' },
  { name: 'Indonesia', code: '+62' },
  { name: 'Philippines', code: '+63' },
  { name: 'Pakistan', code: '+92' },
  { name: 'Bangladesh', code: '+880' },
  { name: 'Haiti', code: '+509' },
  { name: 'Dominican Republic', code: '+1-809' },
];
